//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoBelediyeV1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yorumlar()
        {
            this.SosyalMedya = new HashSet<SosyalMedya>();
        }
    
        public int Yorum_ID { get; set; }
        public Nullable<int> Kullanici_ID { get; set; }
        public Nullable<int> Yetkili_ID { get; set; }
        public string YorumDesc { get; set; }
        public int Likee { get; set; }
        public int Dislike { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<int> Adres_ID { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SosyalMedya> SosyalMedya { get; set; }
        public virtual SosyalMedyaEkibi SosyalMedyaEkibi { get; set; }
    }
}
